baseURL = 'https://grozoiu.com'
languageCode = 'en-us'
title = 'Bogdan Grozoiu'
theme = 'lightbi-hugo'


[Params] 
mainSections = ["azure"]
dateFormat = "2 January"
comments = false
readingTime = true
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"

[Author]
  name = "Bogdan Grozoiu"
  website = "https://grozoiu.com/"
  about = "/about/"
  email = "bogdan@grozoiu.com"
  twitter = "bogdangr"
  linkedin = "bogdan-grozoiu"
  github = "bogdan-grozoiu"
  picture = "/img/about/bogdan-gabriel-grozoiu.jpeg"
  role = "Cloud Solution Architect"


[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Azure"
    url = "/azure/"
    weight = 2

[[menu.main]]
    name = "DevSecOps"
    url = "/devsecops/"
    weight = 3

[[menu.main]]
    name = "Corp Life"
    url = "/corplife/"
    weight = 4